apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-store-v0-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kv-store-v0
  template:
    metadata:
      labels:
        app: kv-store-v0
    spec:
      containers:
        - name: kv-store-minikube-context
          image: kv-store-minikube-context:latest
          ports:
            - containerPort: 9090
          imagePullPolicy: Never
