apiVersion: v1
kind: Service
metadata:
  name: kv-store-v0-service

spec:
  type: NodePort
  selector:
    app:  kv-store-v0

  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30007